sudo: required
services:
  - docker

before_install:
  - cd ./app
  - export DEV=true
  - docker-compose build

script:
  - docker-compose run --rm app sh -c "pylint"
  - docker-compose run --rm app sh -c "./app/wait_for_db.sh && coverage run --source=pytest ./app/tests"

after_script:
  - export DEV=false

after_success:
  - docker-compose run --rm app sh -c "coveralls"