version: "3.9"

services:
  db:
    image: mysql:8.0.32-debian
    container_name: mysql
    # env_file:
    #   - ./app/.env
    environment:
      - MYSQL_DATABASE=${DEV_DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      args:
        - DEV=${DEV}
    # env_file:
    #   - ./app/.env
    environment:
      - DEV=${DEV}
      - SECRET_KEY=${SECRET_KEY}
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEV_DB_NAME=${DEV_DB_NAME}
      - PROD_DB_NAME=${PROD_DB_NAME}
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    command: >
      sh -c "./wait_for_db.sh && flask run --host=0.0.0.0"
    depends_on:
      - db

volumes:
  mysql_data: