version: "3.9"

services:
  db:
    image: mysql:8.0.32-debian
    container_name: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DEV_DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      args:
        - DEV=false
    container_name: flask
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    command: >
      sh -c "./wait_for_db.sh && flask run --host=0.0.0.0"
    depends_on:
      - db

volumes:
  mysql_data: